### ISSUE TITLE
Horseshoe speed and armor values are constantly changing. 

### ISSUE THREAD

**Issue by HyperPigeon** [HyperPigeon/Horseshoes#17]
![image](https://github.com/user-attachments/assets/d8fad579-8127-4a40-9118-6dc9c9cbeb7d)

**Comment by Psychodeus** [comment]
Yes it is fluctuate, to better see it just install Better F3 mod, and activate the actual speed options, then run them horses.

**Comment by Psychodeus** [comment]
https://streamable.com/jwa1w9
See the absolute velocity on top-left
